name: Test the action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - uses: actions/checkout@v3

    - name: Execute action
      id: run
      uses: ./
      with:
        filename: ./.github/workflows/info.xml

    - name: Get the result
      run: |
        echo -e "Versions :\n${{ steps.run.outputs.versions }}"
        echo -e "Branches :\n${{ steps.run.outputs.branches }}"
        echo -e "Matrix :\n${{ steps.run.outputs.matrix }}"
